The World of Ice and Fire:
  Shows Missing (TVDb IDs):
    433631: 'A Knight of the Seven Kingdoms: The Hedge Knight'
Doctor Who Universe:
  Shows Missing (TVDb IDs):
    76107: Doctor Who
    72710: K·9 and Company
    79708: The Sarah Jane Adventures
    122651: K·9
    197071: Sarah Jane's Alien Files
    309893: Class
    444613: The War Between the Land and the Sea
Arrowverse:
  Shows Missing (TVDb IDs):
    257655: Arrow
    279121: The Flash (2014)
    273690: Constantine
    298305: Vixen
    295759: Supergirl
    295760: DC's Legends of Tomorrow
    328982: 'Freedom Fighters: The Ray'
    332525: Black Lightning
    361315: Batwoman
The Boys Universe:
  Shows Missing (TVDb IDs):
    413188: 'The Boys Presents: Diabolical'
    452582: Vought Rising
Marvel Cinematic Universe:
  Shows Missing (TVDb IDs):
    393201: I Am Groot
    412432: X-Men '97
    422712: 'Daredevil: Born Again'
    393204: Ironheart
    443358: Eyes of Wakanda
    412428: Marvel Zombies
    451834: Nova (2025)
    426606: Vision Quest
    428629: Wonder Man
