Final Destination:
  Movies Missing (TMDb IDs):
    9286: Final Destination 3 (2006)
    9358: Final Destination 2 (2003)
    9532: Final Destination (2000)
    19912: The Final Destination (2009)
    55779: Final Destination 5 (2011)
    574475: 'Final Destination 6: Bloodlines'
Resident Evil:
  Movies Missing (TMDb IDs):
    71679: 'Resident Evil: Retribution (2012)'
    35791: 'Resident Evil: Afterlife (2010)'
    1576: Resident Evil (2002)
    1577: 'Resident Evil: Apocalypse (2004)'
    7737: 'Resident Evil: Extinction (2007)'
    173897: 'Resident Evil: The Final Chapter (2016)'
    460458: 'Resident Evil: Welcome to Raccoon City (2021)'
How to Train Your Dragon:
  Movies Missing (TMDb IDs):
    10191: How to Train Your Dragon (2010)
    82702: How to Train Your Dragon 2 (2014)
    166428: 'How to Train Your Dragon: The Hidden World (2019)'
Men In Black:
  Movies Missing (TMDb IDs):
    607: Men in Black (1997)
    608: Men in Black II (2002)
    41154: Men in Black 3 (2012)
John Wick:
  Movies Missing (TMDb IDs):
    730629: 'John Wick: Chapter 5'
Independence Day:
  Movies Missing (TMDb IDs):
    602: Independence Day (1996)
    47933: 'Independence Day: Resurgence (2016)'
The MonsterVerse:
  Movies Missing (TMDb IDs):
    823464: 'Godzilla x Kong: The New Empire (2024)'
Frozen:
  Movies Missing (TMDb IDs):
    109445: Frozen (2013)
    330457: Frozen II (2019)
    1024604: Frozen III
Paddington:
  Movies Missing (TMDb IDs):
    516729: Paddington in Peru
Alice in Wonderland:
  Movies Missing (TMDb IDs):
    12155: Alice in Wonderland (2010)
    241259: Alice Through the Looking Glass (2016)
Extraction:
  Movies Missing (TMDb IDs):
    1141700: Extraction 3
DC Extended Universe:
  Movies Missing (TMDb IDs):
    572802: Aquaman and the Lost Kingdom (2023)
    565770: Blue Beetle (2023)
Goosebumps:
  Movies Missing (TMDb IDs):
    442062: 'Goosebumps 2: Haunted Halloween (2018)'
    257445: Goosebumps (2015)
Child's Play:
  Movies Missing (TMDb IDs):
    10585: Child's Play (1988)
    11186: Child's Play 2 (1990)
    11187: Child's Play 3 (1991)
    11249: Seed of Chucky (2004)
    11932: Bride of Chucky (1998)
    167032: Curse of Chucky (2013)
    393345: Cult of Chucky (2017)
    533642: Child's Play (2019)
A Dog's Purpose:
  Movies Missing (TMDb IDs):
    381289: A Dog's Purpose (2017)
    522518: A Dog's Journey (2019)
Deadpool:
  Movies Missing (TMDb IDs):
    533535: Deadpool 3 (2024)
    567604: Once Upon a Deadpool (2018)
47 Meters Down:
  Movies Missing (TMDb IDs):
    403119: 47 Meters Down (2017)
    480105: '47 Meters Down: Uncaged (2019)'
Pacific Rim:
  Movies Missing (TMDb IDs):
    68726: Pacific Rim (2013)
    268896: 'Pacific Rim: Uprising (2018)'
Peter Rabbit:
  Movies Missing (TMDb IDs):
    381719: Peter Rabbit (2018)
    522478: 'Peter Rabbit 2: The Runaway (2021)'
Happy Death Day:
  Movies Missing (TMDb IDs):
    440021: Happy Death Day (2017)
    512196: Happy Death Day 2U (2019)
    774079: Happy Death Day to Us
Spider-Verse:
  Movies Missing (TMDb IDs):
    911916: 'Spider-Man: Beyond the Spider-Verse'
Marvel Cinematic Universe:
  Movies Missing (TMDb IDs):
    413279: Team Thor (2016)
    441829: 'Team Thor: Part 2 (2017)'
    505945: Team Darryl (2018)
    894205: Werewolf by Night (2022)
28 ... Later:
  Movies Missing (TMDb IDs):
    170: 28 Days Later (2002)
    1562: 28 Weeks Later (2007)
Before...:
  Movies Missing (TMDb IDs):
    76: Before Sunrise (1995)
    80: Before Sunset (2004)
    132344: Before Midnight (2013)
Bad Boys:
  Movies Missing (TMDb IDs):
    573435: Bad Boys 4 (2024)
Honey, I Shrunk the Kids:
  Movies Missing (TMDb IDs):
    9354: Honey, I Shrunk the Kids (1989)
    11158: Honey, I Blew Up the Kid (1992)
    11425: Honey, We Shrunk Ourselves (1997)
Hocus Pocus:
  Movies Missing (TMDb IDs):
    10439: Hocus Pocus (1993)
    642885: Hocus Pocus 2 (2022)
    1136067: Hocus Pocus 3
Avatar:
  Movies Missing (TMDb IDs):
    76600: 'Avatar: The Way of Water (2022)'
    83533: Avatar 3 (2025)
    216527: Avatar 4 (2029)
    19995: Avatar (2009)
    393209: Avatar 5 (2031)
