The Conjuring Universe:
  Movies Missing (TMDb IDs):
    968051: The Nun II (2023)
John Wick:
  Movies Missing (TMDb IDs):
    730629: 'John Wick: Chapter 5'
The MonsterVerse:
  Movies Missing (TMDb IDs):
    823464: Untitled Godzilla vs. Kong Sequel (2024)
Paddington:
  Movies Missing (TMDb IDs):
    516729: Paddington in Peru
DC Extended Universe:
  Movies Missing (TMDb IDs):
    572802: Aquaman and the Lost Kingdom (2023)
    298618: The Flash (2023)
    565770: Blue Beetle (2023)
Child's Play:
  Movies Missing (TMDb IDs):
    10585: Child's Play (1988)
    11186: Child's Play 2 (1990)
    11187: Child's Play 3 (1991)
    11249: Seed of Chucky (2004)
    11932: Bride of Chucky (1998)
    167032: Curse of Chucky (2013)
    393345: Cult of Chucky (2017)
    533642: Child's Play (2019)
A Dog's Purpose:
  Movies Missing (TMDb IDs):
    381289: A Dog's Purpose (2017)
    522518: A Dog's Journey (2019)
Deadpool:
  Movies Missing (TMDb IDs):
    533535: Deadpool 3 (2024)
    567604: Once Upon a Deadpool (2018)
47 Meters Down:
  Movies Missing (TMDb IDs):
    403119: 47 Meters Down (2017)
    480105: '47 Meters Down: Uncaged (2019)'
Marvel Cinematic Universe:
  Movies Missing (TMDb IDs):
    609681: The Marvels (2023)
    447365: Guardians of the Galaxy Vol. 3 (2023)
    617126: Fantastic Four (2025)
    617127: Blade (2024)
    533535: Deadpool 3 (2024)
    822119: 'Captain America: Brave New World (2024)'
Before...:
  Movies Missing (TMDb IDs):
    76: Before Sunrise (1995)
    80: Before Sunset (2004)
    132344: Before Midnight (2013)
Bad Boys:
  Movies Missing (TMDb IDs):
    573435: Bad Boys Forever
Honey, I Shrunk the Kids:
  Movies Missing (TMDb IDs):
    9354: Honey, I Shrunk the Kids (1989)
    11158: Honey, I Blew Up the Kid (1992)
    11425: Honey, We Shrunk Ourselves (1997)
Hocus Pocus:
  Movies Missing (TMDb IDs):
    10439: Hocus Pocus (1993)
    642885: Hocus Pocus 2 (2022)
    1136067: Hocus Pocus 3
Avatar:
  Movies Missing (TMDb IDs):
    76600: 'Avatar: The Way of Water (2022)'
    83533: Avatar 3 (2025)
    216527: Avatar 4 (2026)
    19995: Avatar (2009)
    393209: Avatar 5 (2028)
28 ... Later:
  Movies Missing (TMDb IDs):
    170: 28 Days Later (2002)
    1562: 28 Weeks Later (2007)
