The Conjuring Universe:
  Movies Missing (TMDb IDs):
    968051: The Nun II (2023)
John Wick:
  Movies Missing (TMDb IDs):
    603692: 'John Wick: Chapter 4 (2023)'
Fantastic Beasts:
  Movies Missing (TMDb IDs):
    422641: Fantastic Beasts 4
    422642: Fantastic Beasts 5
The MonsterVerse:
  Movies Missing (TMDb IDs):
    823464: Untitled Godzilla vs. Kong Sequel (2024)
Paddington:
  Movies Missing (TMDb IDs):
    516729: Paddington in Peru
DC Extended Universe:
  Movies Missing (TMDb IDs):
    594767: Shazam! Fury of the Gods (2023)
    572802: Aquaman and the Lost Kingdom (2023)
    298618: The Flash (2023)
    863808: Black Canary
    565770: Blue Beetle (2023)
Deadpool:
  Movies Missing (TMDb IDs):
    533535: Deadpool 3 (2024)
    567604: Once Upon a Deadpool (2018)
Marvel Cinematic Universe:
  Movies Missing (TMDb IDs):
    505642: 'Black Panther: Wakanda Forever (2022)'
    609681: The Marvels (2023)
    774752: The Guardians of the Galaxy Holiday Special
    640146: 'Ant-Man and the Wasp: Quantumania (2023)'
    447365: Guardians of the Galaxy Vol. 3 (2023)
    617126: Fantastic Four (2025)
    617127: Blade (2023)
    533535: Deadpool 3 (2024)
    822119: 'Captain America: New World Order (2024)'
