# Workflow to compress images on demand and every Sunday at 11pm.
# Opens a Pull Request if any images can be compressed.

name: Compress Images

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * 0'

jobs:
  build:
    name: Compress Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Run Image Compression
        id: compress_images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true

      - name: Create Pull Request If Needed
        if: steps.compress_images.outputs.markdown != ''
        uses: peter-evans/create-pull-request@main
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.compress_images.outputs.markdown }}
